defaults:
  - _self_
  - dataset: fasion_mnist
  - model: unet

hydra:
  job:
    chdir: false
  output_subdir: 

# wandb parameters 
wandb:
  entity: luke_and_xingjian
  project: 'DEQ+Diffusion toy experiments'
  notes: 'one toy experiment'
  job_type: training


device: 'cuda'
seed: null

optimizer:
  type: Adam
  _target_: torch.optim.Adam
  lr: 0.001

training:
  epochs: 10
  save_every: 1
  eval_every: 1
  visualize_every: 1
  loss: "huber"
  
scheduler:
  type: 'cosine'
  timesteps: 200